"""Ajout des champs booléens à Parcelle

Revision ID: e442148eea2b
Revises: 
Create Date: 2025-06-21 11:54:00.500187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e442148eea2b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parcelles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fertilisation', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('irrigation', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('controle_ravageurs', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parcelles', schema=None) as batch_op:
        batch_op.drop_column('controle_ravageurs')
        batch_op.drop_column('irrigation')
        batch_op.drop_column('fertilisation')

    # ### end Alembic commands ###
