"""Ajout des date_semis, date_germination, date_croissance_vegetation, date_floraison

Revision ID: e4d9bab87ba9
Revises: e442148eea2b
Create Date: 2025-06-21 13:38:10.282758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4d9bab87ba9'
down_revision = 'e442148eea2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parcelles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_germination', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('date_croissance_vegetative', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('date_floraison', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parcelles', schema=None) as batch_op:
        batch_op.drop_column('date_floraison')
        batch_op.drop_column('date_croissance_vegetative')
        batch_op.drop_column('date_germination')

    # ### end Alembic commands ###
